version: "3.7"

services:
  api:
    image: flask-api:latest
    build: "./api"
    container_name: "flask-api"
    restart: always
    working_dir: /agile-sales
    command: flask run --host=0.0.0.0
    ports:
      - 5000:5000
    expose:
      - "5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: "db-sales"
    volumes:
      - sales-postgres-data:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales_database
    ports:
      - 5432:5432
    expose:
      - "5432"

  front-end:
    build: "./front-end"
    image: sales-front:latest
    container_name: "sales-front"
    command: npm start
    ports:
    - 3000:3000
    expose:
      - "3000"
    depends_on:
      - api
    stdin_open: true

volumes:
  sales-postgres-data:
