version: "3.7"

services:
  postgres:
    image: postgres:latest
    volumes:
      - sales-postgres-data:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales_database
    ports:
      - 5432:5432

volumes:
  sales-postgres-data:
